name: Publish package to the Maven Central Repository & Docker Hub
on:
  release:
    types: [created]
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Build project
        run: mvn -B -ntp package
      - name: Get the tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV
      - name: Set version from git tag
        run: mvn -B -ntp versions:set -DgenerateBackupPoms=false -DnewVersion="$TAG"
      - name: Import gpg secret key
        run: |
          cat <(echo -e "${{ secrets.OSSRH_GPG_SECRET_KEY }}") | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG
      - name: Publish maven package
        run: |
          mvn \
          --no-transfer-progress \
          --batch-mode \
          -Dgpg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} \
          -P ossrh \
          clean deploy
        env:
          MAVEN_USERNAME: kilmajster
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      - name: Build docker init container
        run: |
          docker build \
          -f src/main/docker/initContainer.Dockerfile \
          -t kilmajster/keycloak-username-password-attribute-authenticator:"$TAG" \
          -t kilmajster/keycloak-username-password-attribute-authenticator:latest \
          .
      - name: Log into Docker Hub
        uses: docker/login-action@v1
        with:
          username: kilmajster
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Push tagged image
        run: docker push kilmajster/keycloak-username-password-attribute-authenticator:"$TAG"
      - name: Push latest image
        run: docker push kilmajster/keycloak-username-password-attribute-authenticator:latest